import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Form } from '../components/form';
import { Settings } from '../components/settings';
import { Result } from '../components/result';
import { Map } from '../components/map';
import classNames from 'classnames';

const Home: NextPage = () => {
  const [settingOpen, setSettingsOpen] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Fahrtkosten</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold  text-left mb-12 w-full max-w-6xl mx-auto">Fahrtkosten</h1>
        <div
          className={classNames(
            'z-10 absolute left-0 top-0 h-full p-8 transition-transform bg-white border shadow-md',
            {
              '-translate-x-full': !settingOpen,
              'translate-x-0': settingOpen,
            }
          )}
        >
          <Settings className="grid  gap-8" />
          <button
            onClick={() => setSettingsOpen((value) => !value)}
            className="absolute right-0 top-4 translate-x-full px-4 py-3 border border-l-0 -ml-px bg-white"
          >
            Settings
          </button>
        </div>
        <div className="md:grid md:grid-cols-2 w-full h-full max-w-6xl mx-auto gap-8 ">
          <div className="mb-8">
            <Form className="mb-8" />
            <Result className="mt-6" />
          </div>
          <Map className="w-full h-[90vw]  md:h-96" />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
